version: 2.1

jobs:
  rubocop:
    docker:
      - image: cimg/ruby:3.3.0
    steps:
      - checkout

      # Macの設定が残ってた場合の対策（重要）
      - run: rm -f .bundle/config

      # bundler バージョン固定
      - run: gem install bundler -v 2.5.9

      # PostgreSQL ライブラリ
      - run:
          name: Install PostgreSQL dev libraries
          command: |
            sudo apt-get update
            sudo apt-get install -y libpq-dev postgresql-client

      - run:
          name: Bundle Install
          command: |
            bundle install --jobs=4 --retry=3

      - run:
          name: Run Rubocop
          command: bundle exec rubocop


  rspec:
    docker:
      - image: cimg/ruby:3.3.0
        environment:
          RAILS_ENV: test
      - image: cimg/postgres:14.10
        name: db
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: test_db
          POSTGRES_PASSWORD: password

    steps:
      - checkout

      # Macのpg_config設定削除（重要）
      - run: rm -f .bundle/config

      - run: gem install bundler -v 2.5.9

      # pgのビルドに必要
      - run:
          name: Install PostgreSQL dev libraries
          command: |
            sudo apt-get update
            sudo apt-get install -y libpq-dev postgresql-client

      - run:
          name: Install Gems
          command: |
            bundle install --jobs=4 --retry=3

      - run:
          name: Setup Database
          command: |
            bundle exec rails db:create
            bundle exec rails db:schema:load

      - run:
          name: Run RSpec Model Specs
          command: bundle exec rspec spec/models


workflows:
  version: 2
  test:
    jobs:
      - rubocop
      - rspec:
          requires:
            - rubocop
