version: 2.1

jobs:
  rubocop:
    docker:
      - image: cimg/ruby:3.3.0
    steps:
      - checkout

      - run:
          name: Install PostgreSQL dev libraries
          command: |
            sudo apt-get update
            sudo apt-get install -y libpq-dev build-essential

      - run:
          name: Install Bundler 2.5.9
          command: |
            gem install bundler -v 2.5.9
            bundle -v

      - run:
          name: Bundle Install
          command: |
            bundle config set --local path 'vendor/bundle'
            bundle config set --local without 'production'
            bundle install --jobs=4 --retry=3

      - run:
          name: Run Rubocop
          command: bundle exec rubocop


  rspec:
    docker:
      - image: cimg/ruby:3.3.0
        environment:
          RAILS_ENV: test
          DATABASE_URL: "postgres://postgres:password@db:5432/test_db"

      - image: cimg/postgres:14.10
        name: db
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: test_db
          POSTGRES_PASSWORD: password

    steps:
      - checkout

      - run:
          name: Install PostgreSQL dev libraries
          command: |
            sudo apt-get update
            sudo apt-get install -y libpq-dev build-essential

      - run:
          name: Install Bundler 2.5.9
          command: |
            gem install bundler -v 2.5.9
            bundle -v

      - run:
          name: Bundle Install
          command: |
            bundle config set --local path 'vendor/bundle'
            bundle config set --local without 'production'
            bundle install --jobs=4 --retry=3

      - run:
          name: Setup Database
          command: |
            bin/rails db:create
            bin/rails db:schema:load

      - run:
          name: Run RSpec (only model specs)
          command: bundle exec rspec spec/models


workflows:
  version: 2
  test:
    jobs:
      - rubocop
      - rspec:
          requires:
            - rubocop
