
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  

development:
  <<: *default
  database: ai_app_development
  username: postgres
  password: password
  host: localhost

test:
  <<: *default
  database: ai_app_test
  username: postgres
  password: password
  host: localhost

production:
  <<: *default

  primary:
    url: <%= ENV['DATABASE_URL'] %>

  cable:
    url: <%= ENV["CABLE_DATABASE_URL"] || ENV["DATABASE_URL"] %>
